/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AgendaForm;

import Agenda2.DBConnect;
import Agenda2.Owner;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;// WE CAN DISPLAY ERROR MESSAGE
/**
 *
 * @author ancy
 */
public class Person extends javax.swing.JFrame {
    
    // VARIABLE DECLARATIONS
    Connection con;
    Statement stmt;
    ResultSet rs;
    int curRow = 0;//record which row is currently loaded

    //Constructor
    public Person() {
        initComponents();
        DoConnect();
    }

    Person(DBConnect db, Owner foundOwner) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void DoConnect( ) {      
        
        try{  
        btnSaveRecord.setEnabled( false );
        btnCancelNewRecord.setEnabled( false );
    //Connect to the database  
    String host = "jdbc:derby://localhost:1527/Test";
    String uName="app";
    String uPass="admin";
    con = DriverManager.getConnection( host, uName, uPass );
    
    stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, 
     ResultSet.CONCUR_UPDATABLE );
    String sql = "SELECT ID,EMAIL,FIRST_NAME,LAST_NAME,TELEPHONE, owner_id FROM app.PERSON";
    rs = stmt.executeQuery( sql );
    
    //MOVE THE CURSOR THE FIRST RECORD AND GET THE DATA
    rs.next();
    int id_col=rs.getInt("ID");
    String ID = Integer.toString(id_col);
    String EMAIL= rs.getString("Email");
    String FIRST = rs.getString("First_Name");
    String LAST = rs.getString("LAST_NAME");
    //int id_o=rs.getInt("OWNER_ID");
    //String OWNER_ID = Integer.toString(id_o);
    //String PICTURE_PATH=rs.getString("Picture_Path");
    String TELEPHONE = rs.getString("Telephone");
    
    
    //int DATA = rs.getInt("data");
    //String TITLE = rs.getString("title");
    //String DESCRIPTION = rs.getString("description");
    //int ID_OWNER = rs.getInt("ID");
    
    
    
   // String p=ID+" "+FIRST+" "+LAST+" "+EMAIL+" "+TELEPHONE;
    //System.out.println(p);   }
    
    //DISPLAY THE FIRST RECORD IN THE TEXTFIELDS
    textID.setText(ID);
    textFirstName.setText(FIRST);
    textLastName.setText(LAST);
    textEmail.setText(EMAIL);
    textTelephone.setText(TELEPHONE);
    
    
      
  }catch ( SQLException err ) {
           JOptionPane.showMessageDialog(Person.this,err.getMessage());}
        

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        TestPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("TestPU").createEntityManager();
        person_1Query = java.beans.Beans.isDesignTime() ? null : TestPUEntityManager.createQuery("SELECT p FROM Person_1 p");
        person_1List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : person_1Query.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jPanelHeader = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelDate = new javax.swing.JPanel();
        textID = new javax.swing.JTextField();
        textFirstName = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textTelephone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelButoane = new javax.swing.JPanel();
        btnUpdateRecord = new javax.swing.JButton();
        btnNewRecord = new javax.swing.JButton();
        btnDeleteRecord = new javax.swing.JButton();
        btnSaveRecord = new javax.swing.JButton();
        btnCancelNewRecord = new javax.swing.JButton();
        jPanelButoane2 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelHeader.setBackground(new java.awt.Color(0, 0, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tasks Planner");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("© 2015 Anca Bobes");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jMainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Person"));
        jMainPanel.setToolTipText("");
        jMainPanel.setPreferredSize(new java.awt.Dimension(837, 700));
        jMainPanel.setVerifyInputWhenFocusTarget(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, person_1List, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${firstName}"));
        columnBinding.setColumnName("First Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${lastName}"));
        columnBinding.setColumnName("Last Name");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${telephone}"));
        columnBinding.setColumnName("Telephone");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${picturePath}"));
        columnBinding.setColumnName("Picture Path");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ownerId}"));
        columnBinding.setColumnName("Owner Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${email}"));
        columnBinding.setColumnName("Email");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);

        jPanelDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelDate.setToolTipText("");
        jPanelDate.setName(""); // NOI18N

        jLabel1.setText("ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Email");

        jLabel5.setText("Telephone");

        javax.swing.GroupLayout jPanelDateLayout = new javax.swing.GroupLayout(jPanelDate);
        jPanelDate.setLayout(jPanelDateLayout);
        jPanelDateLayout.setHorizontalGroup(
            jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDateLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDateLayout.createSequentialGroup()
                        .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDateLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(58, 58, 58))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDateLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelDateLayout.createSequentialGroup()
                        .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        jPanelDateLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textEmail, textFirstName, textID, textLastName, textTelephone});

        jPanelDateLayout.setVerticalGroup(
            jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDateLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanelDateLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textEmail, textFirstName, textID, textLastName, textTelephone});

        jPanelButoane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnUpdateRecord.setText("Update Record");
        btnUpdateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRecordActionPerformed(evt);
            }
        });

        btnNewRecord.setText("New Record");
        btnNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewRecordActionPerformed(evt);
            }
        });

        btnDeleteRecord.setText("Delete Record");
        btnDeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRecordActionPerformed(evt);
            }
        });

        btnSaveRecord.setText("Save Record");
        btnSaveRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRecordActionPerformed(evt);
            }
        });

        btnCancelNewRecord.setText("Cancel Record");
        btnCancelNewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNewRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButoaneLayout = new javax.swing.GroupLayout(jPanelButoane);
        jPanelButoane.setLayout(jPanelButoaneLayout);
        jPanelButoaneLayout.setHorizontalGroup(
            jPanelButoaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButoaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButoaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateRecord)
                    .addComponent(btnDeleteRecord)
                    .addGroup(jPanelButoaneLayout.createSequentialGroup()
                        .addComponent(btnNewRecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelNewRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaveRecord)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanelButoaneLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteRecord, btnNewRecord, btnUpdateRecord});

        jPanelButoaneLayout.setVerticalGroup(
            jPanelButoaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButoaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButoaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewRecord)
                    .addComponent(btnCancelNewRecord)
                    .addComponent(btnSaveRecord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteRecord))
        );

        jPanelButoaneLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDeleteRecord, btnNewRecord, btnUpdateRecord});

        jPanelButoane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelButoane2Layout = new javax.swing.GroupLayout(jPanelButoane2);
        jPanelButoane2.setLayout(jPanelButoane2Layout);
        jPanelButoane2Layout.setHorizontalGroup(
            jPanelButoane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelButoane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelButoane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57)
                .addGroup(jPanelButoane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanelButoane2Layout.setVerticalGroup(
            jPanelButoane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelButoane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelButoane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnFirst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelButoane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnLast)))
        );

        jButton1.setText("Go to Event Window");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jMainPanelLayout = new javax.swing.GroupLayout(jMainPanel);
        jMainPanel.setLayout(jMainPanelLayout);
        jMainPanelLayout.setHorizontalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelButoane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelButoane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        jMainPanelLayout.setVerticalGroup(
            jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jMainPanelLayout.createSequentialGroup()
                        .addComponent(jPanelButoane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelButoane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jPanelDate.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
//MOVE TO THE NEXT RECOD
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        try {
            if ( rs.next( ) ) {
                 int id_col=rs.getInt("ID");
                 String ID = Integer.toString(id_col);
                 String EMAIL= rs.getString("Email");
                 String FIRST = rs.getString("First_Name");
                 String LAST = rs.getString("LAST_NAME");
                 String TELEPHONE = rs.getString("Telephone");

                textID.setText(ID);
                textFirstName.setText(FIRST);
                textLastName.setText(LAST);
                textEmail.setText(EMAIL);
                textTelephone.setText(TELEPHONE);

              }
            else {
                 rs.previous( );
                 JOptionPane.showMessageDialog(Person.this, "End of File");
                 }
               }
         catch (SQLException err) {
                 JOptionPane.showMessageDialog(Person.this, err.getMessage());
                                   }


    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        try {
            if ( rs.previous( ) ) {
                 int id_col=rs.getInt("ID");
                 String ID = Integer.toString(id_col);
                 String EMAIL= rs.getString("Email");
                 String FIRST = rs.getString("First_Name");
                 String LAST = rs.getString("LAST_NAME");
                 String TELEPHONE = rs.getString("Telephone");

                textID.setText(ID);
                textFirstName.setText(FIRST);
                textLastName.setText(LAST);
                textEmail.setText(EMAIL);
                textTelephone.setText(TELEPHONE);

              }
            else {
                 rs.next( );
                 JOptionPane.showMessageDialog(Person.this, "Start of file!");
                 }
               }
         catch (SQLException err) {
                 JOptionPane.showMessageDialog(Person.this, err.getMessage());
                                   }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
       
          try {
           rs.first( );
                 int id_col=rs.getInt("ID");
                 String ID = Integer.toString(id_col);
                 String EMAIL= rs.getString("Email");
                 String FIRST = rs.getString("First_Name");
                 String LAST = rs.getString("LAST_NAME");
                 String TELEPHONE = rs.getString("Telephone");

                textID.setText(ID);
                textFirstName.setText(FIRST);
                textLastName.setText(LAST);
                textEmail.setText(EMAIL);
                textTelephone.setText(TELEPHONE);
               }
         catch (SQLException err) {
                 JOptionPane.showMessageDialog(Person.this, err.getMessage());
                                   }
        
          
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        try {
           rs.last( );
                 int id_col=rs.getInt("ID");
                 String ID = Integer.toString(id_col);
                 String EMAIL= rs.getString("Email");
                 String FIRST = rs.getString("First_Name");
                 String LAST = rs.getString("LAST_NAME");
                 String TELEPHONE = rs.getString("Telephone");

                textID.setText(ID);
                textFirstName.setText(FIRST);
                textLastName.setText(LAST);
                textEmail.setText(EMAIL);
                textTelephone.setText(TELEPHONE);
               }
         catch (SQLException err) {
                 JOptionPane.showMessageDialog(Person.this, err.getMessage());
                                   }
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnDeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRecordActionPerformed
        try{
            rs.deleteRow( );
            
            stmt.close( );
            rs.close( );
        
            stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, 
            ResultSet.CONCUR_UPDATABLE );
            String sql = "SELECT ID,EMAIL,FIRST_NAME,LAST_NAME,TELEPHONE FROM app.PERSON";
            rs = stmt.executeQuery( sql );
    
    //MOVE THE
           rs.next();
           int id_col=rs.getInt("ID");
            String id = Integer.toString(id_col);
            String EMAIL= rs.getString("Email");
            String FIRST = rs.getString("First_Name");
            String LAST = rs.getString("LAST_NAME");
            String TELEPHONE = rs.getString("Telephone");
   
    
    //DISPLAY THE FIRST RECORD IN THE TEXTFIELDS
           textID.setText(id);
           textFirstName.setText(FIRST);
           textLastName.setText(LAST);
           textEmail.setText(EMAIL);
           textTelephone.setText(TELEPHONE);         
           }catch ( SQLException err ) {
               JOptionPane.showMessageDialog(Person.this,err.getMessage());
                                        }
    }//GEN-LAST:event_btnDeleteRecordActionPerformed

    private void btnUpdateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRecordActionPerformed
        String first = textFirstName.getText( );
        String last = textLastName.getText( );
        String telephone = textTelephone.getText( );
        String email = textEmail.getText();
        String ID = textID.getText( );
        
        //IF WE WANT TO UPDATE AN ID FIELD, WE NEED TO CONVERT THE STRING TO INTEGER
        //The Integer object has a method called parseInt
        int newID = Integer.parseInt( ID );//type the string that you're trying to convert
        
        try {
             rs.updateInt( "ID", newID );
             rs.updateString( "First_Name", first );
             rs.updateString( "last_Name", last );
             rs.updateString( "Email", email );
             rs.updateString("Telephone", telephone);
             rs.updateRow( );
            JOptionPane.showMessageDialog(Person.this, "Updated");
             }
        catch (SQLException err) {
              System.out.println(err.getMessage() );
                                  }
        
    }//GEN-LAST:event_btnUpdateRecordActionPerformed

    private void btnSaveRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRecordActionPerformed
       
        String first=textFirstName.getText();
        String last=textLastName.getText();
        String email = textEmail.getText();
        String telephone = textTelephone.getText();
        String ID = textID.getText();
        int newID=Integer.parseInt(ID);
        
        
        try{
            rs.moveToInsertRow( );// Insert Row CREATES A BLANK RECORD IN THE ResultSet
            
            rs.updateInt("ID", newID);
            rs.updateString("First_Name", first);// adding DATA to the ResultSet
            rs.updateString("Last_Name", last);
            rs.updateString("Email", email);
            rs.updateString("telephone", telephone);
            rs.updateInt("OWNER_ID", 1);
            
            rs.insertRow( ); // INSERT a NEW row
            
            stmt.close( );
            rs.close( );
        
            stmt = con.createStatement( ResultSet.TYPE_SCROLL_INSENSITIVE, 
            ResultSet.CONCUR_UPDATABLE );
            String sql = "SELECT ID,EMAIL,FIRST_NAME,LAST_NAME,TELEPHONE FROM app.PERSON";
            rs = stmt.executeQuery( sql );
    
    //MOVE THE
    rs.next();
    int id_col=rs.getInt("ID");
    String id = Integer.toString(id_col);
    String EMAIL2= rs.getString("Email");
    String FIRST2 = rs.getString("First_Name");
    String LAST2 = rs.getString("LAST_NAME");
    //int id_o=rs.getInt("OWNER_ID");
    //String OWNER_ID = Integer.toString(id_o);
    //String PICTURE_PATH=rs.getString("Picture_Path");
    String TELEPHONE2 = rs.getString("Telephone");
    
    
    //int DATA = rs.getInt("data");
    //String TITLE = rs.getString("title");
    //String DESCRIPTION = rs.getString("description");
    //int ID_OWNER = rs.getInt("ID");
    
    
    
   // String p=ID+" "+FIRST+" "+LAST+" "+EMAIL+" "+TELEPHONE;
    //System.out.println(p);   }
    
    //DISPLAY THE FIRST RECORD IN THE TEXTFIELDS
    textID.setText(id);
    textFirstName.setText(FIRST2);
    textLastName.setText(LAST2);
    textEmail.setText(EMAIL2);
    textTelephone.setText(TELEPHONE2);
    
        btnFirst.setEnabled(true);
        btnPrevious.setEnabled(true);
        btnNext.setEnabled(true);
        btnLast.setEnabled(true);
        btnUpdateRecord.setEnabled(true);
        btnDeleteRecord.setEnabled(true);
        btnNewRecord.setEnabled(true);
        
        btnSaveRecord.setEnabled(false);
        btnCancelNewRecord.setEnabled(false);
    //DefaultTableModel model = (DefaultTableModel) emp_table.getModel();
//model.AddRow();   
           }catch ( SQLException err ) {
               JOptionPane.showMessageDialog(Person.this,err.getMessage());
                                        }
       
    }//GEN-LAST:event_btnSaveRecordActionPerformed

    private void btnNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewRecordActionPerformed
        try{
            curRow = rs.getRow( );
        //CLEAR THE TEXT FIELDS
        textFirstName.setText("");
        textLastName.setText("");
        textEmail.setText("");
        textTelephone.setText("");
        textID.setText("");
        
        
        btnFirst.setEnabled( false );
        btnPrevious.setEnabled( false ) ;
        btnNext.setEnabled( false );
        btnLast.setEnabled( false );
        btnUpdateRecord.setEnabled( false );
        btnDeleteRecord.setEnabled( false );
        btnNewRecord.setEnabled( false );

        btnSaveRecord.setEnabled( true );
        btnCancelNewRecord.setEnabled( true );
        }
        catch (SQLException err) {
                 JOptionPane.showMessageDialog(Person.this, err.getMessage());
                                   }     
        
    }//GEN-LAST:event_btnNewRecordActionPerformed

    private void btnCancelNewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNewRecordActionPerformed
               
        try{
        //The absolute method moves the Cursor to a fixed position in the ResultSet    
            rs.absolute( curRow );
        textFirstName.setText(rs.getString("First_Name"));
        textLastName.setText(rs.getString("Last_Name"));
        textEmail.setText(rs.getString("Email"));
        textTelephone.setText(rs.getString("Telephone"));
        textID.setText(rs.getString("ID"));
 
        
        btnFirst.setEnabled( true );
        btnPrevious.setEnabled( true ) ;
        btnNext.setEnabled( true );
        btnLast.setEnabled( true );
        btnUpdateRecord.setEnabled( true );
        btnDeleteRecord.setEnabled( true );
        btnNewRecord.setEnabled( true );

        btnSaveRecord.setEnabled( false );
        btnCancelNewRecord.setEnabled( false );
        }
        catch (SQLException err) {
                 JOptionPane.showMessageDialog(Person.this, err.getMessage());
                                   }     
    }//GEN-LAST:event_btnCancelNewRecordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Event e = new Event();
        e.setDefaultCloseOperation(Event.DISPOSE_ON_CLOSE);
        e.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Person.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Person.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Person.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Person.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Person().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager TestPUEntityManager;
    private javax.swing.JButton btnCancelNewRecord;
    private javax.swing.JButton btnDeleteRecord;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNewRecord;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSaveRecord;
    private javax.swing.JButton btnUpdateRecord;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jMainPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelButoane;
    private javax.swing.JPanel jPanelButoane2;
    private javax.swing.JPanel jPanelDate;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.util.List<AgendaForm.Person_1> person_1List;
    private javax.persistence.Query person_1Query;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textTelephone;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
